channels:
- conda-forge
dependencies:
- python=3.10.6
- pip<=21.3.1
- pip:
  - mlflow<3,>=2.2
  - cloudpickle==2.2.1
  - numpy==1.23.5
  - psutil==5.9.4
  - scikit-learn==1.2.1
  - scipy==1.10.1
  - typing-extensions==4.5.0
name: mlflow-env
